version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=250591
      - POSTGRES_DB=job_listings_db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=250591
      - POSTGRES_DB=job_listings_db